### ISSUE TITLE
Lots of sign conversion warnings from compiler

### ISSUE THREAD

**Issue by boxerab** [gabime/spdlog#1506]
First of all, thanks for making this incredible library available!

I am using spdlog in my image codec library, and when I compiler I get many
[sign-conversion warnings](https://my.cdash.org/viewBuildError.php?type=1&buildid=1803285)

Are there plans to address these warnings?

Thanks!

**Comment by gabime** [comment]
> First of all, thanks for making this incredible library available!

Thanks!

Which version are you using?Those warnings come from the fmt library, and some of them were already fixed by the fmt project
I suggest to try latest spdlog commit , it disables warnings by default when building with cmake.

**Comment by boxerab** [comment]
> Which version are you using?Those warnings come from the fmt library, and some of them were already fixed by the fmt project
> I suggest to try latest spdlog commit , it disables warnings by default when building with cmake.

Thanks. My project uses cmake, but I am using spdlog headers. Can I turn off fmt warnings in my cmake file? Also, hopefully fmt proj will fix the warnings, as they often point to bugs.

**Comment by gabime** [comment]
There is new flag in the cmake for this: ```-DSPDLOG_ENABLE_WARNINGS=OFF```

**Comment by boxerab** [comment]
Thanks, unfortunately I still get these warnings, from the `clang` compiler.

**Comment by boxerab** [comment]
I have `-Wall` turned on, btw.

**Comment by gabime** [comment]
Try to disable them using pragmas before including  spdlog.h then.

**Comment by boxerab** [comment]
The latest version of `fmt` library fixes a number of warnings - is there a plan to upgrade to fmt 6.20 ?

**Comment by tt4g** [comment]
@boxerab Bundled fmt has been update to 6.2.0 by this commit: 7698bb0ae1029ffa0b97b7924adba50e2f9bac43

**Comment by boxerab** [comment]
Perfect! This fixed all of the warnings I was seeing from spdlog.
