### ISSUE TITLE
Color logs

### ISSUE THREAD

**Issue by YosefMac** [gabime/spdlog#378]
This is really a question instead that a issue, I could not find in the API methods to able print with a specific color rather that use `spd::stdout_color_mt` and the logs levels with the defaults colors. Exist any API that I can use to log with different colors? Specifying the color with a flag or arg

Thanks in advance!!

**Comment by gabime** [comment]
No. There is no way except for editing the source.

**Comment by adamcavendish** [comment]
However, it might be simplified by using constexpr in a header for clean editing.

**Comment by henryiii** [comment]
Have you thought about using the rang library? It's a small, header only library that supports color (basic 8 color + styles only last I checked) on all platforms. The reason I ask is that when trying to use this library instead of rang + cout, I end up getting raw color codes where before the colors "worked" (i.e., they didn't print in color or spit out error codes).

**Comment by gabime** [comment]
@henryiii No, never heard of it. Will check it out. 
In which platform did you see the problem?

**Comment by henryiii** [comment]
@gabime Xcode terminal on Mac. It is a really basic terminal and doesn't support colors, so the colors should automatically turn off.

It looks like the code that makes rang work is [here](https://github.com/agauniyal/rang/blob/7f2143809b9ac90a1a8a2e779fb357d8709448c2/include/rang.hpp#L123-L137).

**Comment by gabime** [comment]
@henryiii Thanks for the link to the code snippet. 
I might copy/paste this function to spdlog to auto turn off colors.

**Comment by henryiii** [comment]
That should work, and agauniyal released it under an unlicense, so you can take anything you'd like. :)

**Comment by aldanor** [comment]
Same question here, what's the best way to disable colors when the output stream is a non-tty or doesn't support color? (ending up with ascii color escape sequences in log files is not cool)

**Comment by gabime** [comment]
Fixed in 1d6842f0f9833db265355fef110a15e596769362. Now spdlog tries to detect if the terminal supports colors before emitting the escape codes.

**Comment by aldanor** [comment]
@gabime With the latest changes, spdlog detects if terminal supports color but it doesn't check if *it's a terminal* in a first place... Minimal example:

```bash
$ env TERM=ansi myprog > log.txt
```
In this case TERM will be set but it's not a tty so colours should be disabled, otherwise you still get a log file full of ansi escape codes.

The relevant part in `rang` library mentioned above is this (`isatty` etc): https://github.com/agauniyal/rang/blob/master/include/rang.hpp#L146

**Comment by gabime** [comment]
Right. Will be fixed

**Comment by agauniyal** [comment]
Windows 10 and above supports the Linux terminal escape codes, but the lower versions don't. I include separate methods and detect lower windows version at run time otherwise garbled text will output on them too. There is another problem of hardcoded linux terminals which is being worked on in develop branch with last issue remaining - https://github.com/agauniyal/rang/issues/60

Currently `rang` is biased towards standard iostreams but do tell me if any change is required to make it easier for you (since I use your lib extensively on personal projects) :)

**Comment by gabime** [comment]
> rang is biased towards standard iostreams

@agauniyal That's why I decided just to copy & [paste](https://github.com/gabime/spdlog/blob/master/include/spdlog/details/os.h#L423-L462) the relevant parts.

I would appreciate if you take a quick look for any potential issues.

**Comment by agauniyal** [comment]
@gabime sure. For windows, I'm guessing you're outputting the escape code always? Prior to windows 10, this will not work as intended and you need to use SetConsoleXXX functions.

For linux, we're hardcoding the terminals here - `"ansi", "color", "console", "cygwin", "gnome", "konsole", "kterm", "linux", "msys", "putty", "rxvt", "screen", "vt100", "xterm"` and while this will cover 90% or more console needs, this ain't foolproof because people do use exotic terminals and tty here and there.

In next version of rang, I'm going to fix these issues as well as modularize the code so that it'll be easier to take out methods and remove the iostream bias. I'll notify once its done 👍

**Comment by gabime** [comment]
@agauniyal For windows spdlog is using the "[wincolor_sink](https://github.com/gabime/spdlog/blob/master/include/spdlog/sinks/wincolor_sink.h)" which indeed uses the setConsoleXXX functions.

**Comment by agauniyal** [comment]
@gabime Cleaned up detection logic which works for all cases. The `supportsColor()` method returns false if windows less than 10 (where ANSI codes aren't supported) is present so you can use your wincolor_sink methods there. Take a look if you want :)

```cpp
#ifndef RANG_DETECT_DOT_HPP
#define RANG_DETECT_DOT_HPP

#if defined(__unix__) || defined(__unix) || defined(__linux__)
#define OS_LINUX
#elif defined(WIN32) || defined(_WIN32) || defined(_WIN64)
#define OS_WIN
#elif defined(__APPLE__) || defined(__MACH__)
#define OS_MAC
#else
#error Unknown Platform
#endif

#if defined(OS_LINUX) || defined(OS_MAC)
#include <unistd.h>
#include <cstring>

#elif defined(OS_WIN)
#include <windows.h>
#include <io.h>
#include <VersionHelpers.h>
#endif

#include <algorithm>
#include <cstdlib>
#include <iostream>

namespace rang {
namespace _implementation {

    inline bool supportsColor() noexcept
    {
#if defined(OS_LINUX) || defined(OS_MAC)

        static const bool result = [] {
            const char *Terms[]
              = { "ansi",    "color",  "console", "cygwin", "gnome",
                  "konsole", "kterm",  "linux",   "msys",   "putty",
                  "rxvt",    "screen", "vt100",   "xterm" };

            const char *env_p = std::getenv("TERM");
            if (env_p == nullptr) {
                return false;
            } else {
                return std::any_of(
                  std::begin(Terms), std::end(Terms), [&](const char *term) {
                      return std::strstr(env_p, term) != nullptr;
                  });
            }
        }();

#elif defined(OS_WIN)
        static const bool result = [] {
            HANDLE h = GetStdHandle(STD_OUTPUT_HANDLE);
            if (h == INVALID_HANDLE_VALUE) {
                return false;
            }
            if (IsWindowsVersionOrGreater(10, 0, 0)) {
                DWORD dwMode = 0;
                if (!GetConsoleMode(h, &dwMode)) {
                    return false;
                }
                dwMode |= ENABLE_VIRTUAL_TERMINAL_PROCESSING;
                if (!SetConsoleMode(h, dwMode)) {
                    return false;
                }
                return true;
            } else {
                return false;
            }
        }();
#endif
        // Don't ignore false result in case of windows < 10, use old setConsoleAttributes functions
        return result;
    }


    inline bool isTerminal(const std::streambuf *osbuf) noexcept
    {
        using std::cerr;
        using std::clog;
        using std::cout;

#if defined(OS_LINUX) || defined(OS_MAC)
        auto fn_tty    = isatty;
        auto fn_fileno = fileno;
#elif defined(OS_WIN)
        auto fn_tty    = _isatty;
        auto fn_fileno = _fileno;
#endif
        static const bool result = [&] {
            if (osbuf == cout.rdbuf()) {
                return fn_tty(fn_fileno(stdout)) ? true : false;
            } else if (osbuf == cerr.rdbuf() || osbuf == clog.rdbuf()) {
                return fn_tty(fn_fileno(stderr)) ? true : false;
            } else {
                return false;
            }
        }();
        return result;
    }
}  // namespace _implementation


namespace detect {
    inline bool isSafe(const std::ostream &os) noexcept
    {
        return _implementation::supportsColor()
          && _implementation::isTerminal(os.rdbuf());
    }
}  // namespace detect
}  // namespace rang

#undef OS_LINUX
#undef OS_WIN
#undef OS_MAC

#endif /* ifndef RANG_DETECT_DOT_HPP */
```

**Comment by gabime** [comment]
@agauniyal Thanks, I will take a look.

**Comment by gabime** [comment]
@agauniyal Shouldn't it be called ```supportsAnsiColors()``` instead of ```supportsColor()```? It got me confused a little bit

**Comment by agauniyal** [comment]
@gabime you're right, I didn't think of windows behavior(the last comment inside that function) before naming that function. Also it's been a while and some additional fixes might've landed to [next-release](https://github.com/agauniyal/rang/blob/next-release/include/rang.hpp) branch so you can check them out :)
